crm_community_messages_homepage:
    pattern:  /alert
    defaults: { _controller: crm_community_messages.default_controller:indexAction }
  
crm_welcome_messages_homepage:
    pattern:  /welcome
    defaults: { _controller: CRMCommunityMessagesBundle:Welcome:index }
